### ISSUE TITLE
有个bug&演示的地址 css文件url 出错，

### ISSUE THREAD

**Issue by rolitter** [jsonpeter/vue2.0-zoom#1]
![image](https://user-images.githubusercontent.com/27326998/33759579-d4894554-dc3d-11e7-9965-dbfd1144c317.png)
放大第一个图片的结束，移入第二个图片的时候，放大区域还是第一张图片
![image](https://user-images.githubusercontent.com/27326998/33759741-5cf8a182-dc3e-11e7-9234-87e31cd4e6f7.png)

**Comment by jsonpeter** [comment]
感谢反馈，问题已修复！ "version": "2.0.3"
